/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScleralLensesRouteImport } from './routes/scleral-lenses'
import { Route as RgpLensesRouteImport } from './routes/rgp-lenses'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostLasikRouteImport } from './routes/post-lasik'
import { Route as KeratoconusRouteImport } from './routes/keratoconus'
import { Route as IrregularCorneaRouteImport } from './routes/irregular-cornea'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScleralLensesRoute = ScleralLensesRouteImport.update({
  id: '/scleral-lenses',
  path: '/scleral-lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const RgpLensesRoute = RgpLensesRouteImport.update({
  id: '/rgp-lenses',
  path: '/rgp-lenses',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLasikRoute = PostLasikRouteImport.update({
  id: '/post-lasik',
  path: '/post-lasik',
  getParentRoute: () => rootRouteImport,
} as any)
const KeratoconusRoute = KeratoconusRouteImport.update({
  id: '/keratoconus',
  path: '/keratoconus',
  getParentRoute: () => rootRouteImport,
} as any)
const IrregularCorneaRoute = IrregularCorneaRouteImport.update({
  id: '/irregular-cornea',
  path: '/irregular-cornea',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/irregular-cornea': typeof IrregularCorneaRoute
  '/keratoconus': typeof KeratoconusRoute
  '/post-lasik': typeof PostLasikRoute
  '/privacy': typeof PrivacyRoute
  '/rgp-lenses': typeof RgpLensesRoute
  '/scleral-lenses': typeof ScleralLensesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/irregular-cornea': typeof IrregularCorneaRoute
  '/keratoconus': typeof KeratoconusRoute
  '/post-lasik': typeof PostLasikRoute
  '/privacy': typeof PrivacyRoute
  '/rgp-lenses': typeof RgpLensesRoute
  '/scleral-lenses': typeof ScleralLensesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/irregular-cornea': typeof IrregularCorneaRoute
  '/keratoconus': typeof KeratoconusRoute
  '/post-lasik': typeof PostLasikRoute
  '/privacy': typeof PrivacyRoute
  '/rgp-lenses': typeof RgpLensesRoute
  '/scleral-lenses': typeof ScleralLensesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/irregular-cornea'
    | '/keratoconus'
    | '/post-lasik'
    | '/privacy'
    | '/rgp-lenses'
    | '/scleral-lenses'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/irregular-cornea'
    | '/keratoconus'
    | '/post-lasik'
    | '/privacy'
    | '/rgp-lenses'
    | '/scleral-lenses'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/irregular-cornea'
    | '/keratoconus'
    | '/post-lasik'
    | '/privacy'
    | '/rgp-lenses'
    | '/scleral-lenses'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  IrregularCorneaRoute: typeof IrregularCorneaRoute
  KeratoconusRoute: typeof KeratoconusRoute
  PostLasikRoute: typeof PostLasikRoute
  PrivacyRoute: typeof PrivacyRoute
  RgpLensesRoute: typeof RgpLensesRoute
  ScleralLensesRoute: typeof ScleralLensesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scleral-lenses': {
      id: '/scleral-lenses'
      path: '/scleral-lenses'
      fullPath: '/scleral-lenses'
      preLoaderRoute: typeof ScleralLensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rgp-lenses': {
      id: '/rgp-lenses'
      path: '/rgp-lenses'
      fullPath: '/rgp-lenses'
      preLoaderRoute: typeof RgpLensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-lasik': {
      id: '/post-lasik'
      path: '/post-lasik'
      fullPath: '/post-lasik'
      preLoaderRoute: typeof PostLasikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keratoconus': {
      id: '/keratoconus'
      path: '/keratoconus'
      fullPath: '/keratoconus'
      preLoaderRoute: typeof KeratoconusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irregular-cornea': {
      id: '/irregular-cornea'
      path: '/irregular-cornea'
      fullPath: '/irregular-cornea'
      preLoaderRoute: typeof IrregularCorneaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  IrregularCorneaRoute: IrregularCorneaRoute,
  KeratoconusRoute: KeratoconusRoute,
  PostLasikRoute: PostLasikRoute,
  PrivacyRoute: PrivacyRoute,
  RgpLensesRoute: RgpLensesRoute,
  ScleralLensesRoute: ScleralLensesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
